apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ranking-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dongjune8931/ScaleRank
    targetRevision: main
    path: infra/k8s/ranking-service
  destination:
    server: https://kubernetes.default.svc
    namespace: scalerank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
