apiVersion: v1
kind: ConfigMap
metadata:
  name: score-service-config
  namespace: scalerank
data:
  PORT: "8080"
  DB_PORT: "3306"
  DB_NAME: "scalerank"
  REDIS_PORT: "6379"
  # DB_HOST, DB_USER, DB_PASSWORD, REDIS_HOST are injected from score-service-secret
